-- 修复Oracle触发器无效问题：重新创建系统时间轴触发器修改测试
CREATE OR REPLACE TRIGGER SYSTEM_TIMELINE_TRIG
BEFORE INSERT OR UPDATE ON SYSTEM_TIMELINE
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    -- 插入时自动生成ID（如果为空）
    IF :NEW.ID IS NULL THEN
      SELECT SYSTEM_TIMELINE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    -- 插入时设置创建时间和更新时间
    IF :NEW.CREATE_TIME IS NULL THEN
      :NEW.CREATE_TIME := SYSDATE;
    END IF;
    :NEW.UPDATE_TIME := SYSDATE;
  END IF;
  
  IF UPDATING THEN
    -- 更新时自动更新更新时间
    :NEW.UPDATE_TIME := SYSDATE;
  END IF;
END;
/