-- 创建系统信息表
CREATE TABLE SYSTEM_INFO (
    ID NUMBER(11) PRIMARY KEY,
    SYSTEM_NAME VARCHAR2(200) NOT NULL,
    FUNCTION_DESC VARCHAR2(1000),
    RESPONSIBLE_PERSON VARCHAR2(100),
    SOURCE VARCHAR2(50),
    TYPE VARCHAR2(50),
    IS_USING VARCHAR2(20),
    CAN_PROMOTE VARCHAR2(20),
    IDLE_FUNCTIONS VARCHAR2(1000),
    CREATE_TIME DATE DEFAULT SYSDATE,
    UPDATE_TIME DATE DEFAULT SYSDATE
);

-- 创建序列
CREATE SEQUENCE SYSTEM_INFO_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE
ORDER;

-- 创建触发器
CREATE OR REPLACE TRIGGER SYSTEM_INFO_TRIG
BEFORE INSERT OR UPDATE ON SYSTEM_INFO
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF :NEW.ID IS NULL THEN
      SELECT SYSTEM_INFO_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    IF :NEW.CREATE_TIME IS NULL THEN
      :NEW.CREATE_TIME := SYSDATE;
    END IF;
    :NEW.UPDATE_TIME := SYSDATE;
  END IF;
  
  IF UPDATING THEN
    :NEW.UPDATE_TIME := SYSDATE;
  END IF;
END;
/