-- 1. 新增系统字段到SYSTEM_TIMELINE表
ALTER TABLE SYSTEM_TIMELINE ADD (SYSTEM_NAME VARCHAR2(200) DEFAULT 'default' NOT NULL);

-- 2. 修改时间轴序列，确保它仍然可用
ALTER SEQUENCE SYSTEM_TIMELINE_SEQ INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;

-- 3. 重新创建触发器，确保它与当前表结构匹配
CREATE OR REPLACE TRIGGER SYSTEM_TIMELINE_TRIG
BEFORE INSERT OR UPDATE ON SYSTEM_TIMELINE
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    IF :NEW.ID IS NULL THEN
      SELECT SYSTEM_TIMELINE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    IF :NEW.CREATE_TIME IS NULL THEN
      :NEW.CREATE_TIME := SYSDATE;
    END IF;
    :NEW.UPDATE_TIME := SYSDATE;
  END IF;
  
  IF UPDATING THEN
    :NEW.UPDATE_TIME := SYSDATE;
  END IF;
END;
/