-- 系统发展时间轴表
CREATE TABLE SYSTEM_TIMELINE (
    -- 主键ID，自增
    ID NUMBER(11) NOT NULL,
    -- 时间轴日期
    EVENT_DATE DATE NOT NULL,
    -- 事件标题
    TITLE VARCHAR2(200) NOT NULL,
    -- 事件描述
    DESCRIPTION VARCHAR2(1000),
    -- 创建时间
    CREATE_TIME DATE DEFAULT SYSDATE,
    -- 更新时间
    UPDATE_TIME DATE DEFAULT SYSDATE,
    -- 主键约束
    CONSTRAINT PK_SYSTEM_TIMELINE PRIMARY KEY (ID)
);

-- 创建序列用于生成主键ID
CREATE SEQUENCE SEQ_SYSTEM_TIMELINE
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

-- 创建触发器用于自动生成主键ID
CREATE OR REPLACE TRIGGER TRG_SYSTEM_TIMELINE_BEFORE_INSERT
BEFORE INSERT ON SYSTEM_TIMELINE
FOR EACH ROW
BEGIN
    -- 如果ID为空，则使用序列生成
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_SYSTEM_TIMELINE.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    -- 设置创建时间和更新时间
    IF :NEW.CREATE_TIME IS NULL THEN
        :NEW.CREATE_TIME := SYSDATE;
    END IF;
    :NEW.UPDATE_TIME := SYSDATE;
END;
/

-- 创建索引优化日期查询
CREATE INDEX IDX_SYSTEM_TIMELINE_DATE ON SYSTEM_TIMELINE(EVENT_DATE DESC);

-- 插入示例数据
INSERT INTO SYSTEM_TIMELINE (EVENT_DATE, TITLE, DESCRIPTION) VALUES
(TO_DATE('2023-01-15', 'YYYY-MM-DD'), '系统上线', '基础业务系统正式上线，包含核心订单处理功能');

INSERT INTO SYSTEM_TIMELINE (EVENT_DATE, TITLE, DESCRIPTION) VALUES
(TO_DATE('2023-03-20', 'YYYY-MM-DD'), '功能升级', '增加了库存管理模块，支持多仓库管理');

INSERT INTO SYSTEM_TIMELINE (EVENT_DATE, TITLE, DESCRIPTION) VALUES
(TO_DATE('2023-06-10', 'YYYY-MM-DD'), '性能优化', '优化了数据库查询，系统响应速度提升30%');

INSERT INTO SYSTEM_TIMELINE (EVENT_DATE, TITLE, DESCRIPTION) VALUES
(TO_DATE('2023-09-05', 'YYYY-MM-DD'), '新功能添加', '上线了报表统计功能，支持多维度数据分析');

INSERT INTO SYSTEM_TIMELINE (EVENT_DATE, TITLE, DESCRIPTION) VALUES
(TO_DATE('2024-01-20', 'YYYY-MM-DD'), '系统重构', '重构了核心代码架构，提高了系统可维护性');

INSERT INTO SYSTEM_TIMELINE (EVENT_DATE, TITLE, DESCRIPTION) VALUES
(TO_DATE('2024-04-15', 'YYYY-MM-DD'), '移动端支持', '增加了移动端适配，支持手机端访问系统');

INSERT INTO SYSTEM_TIMELINE (EVENT_DATE, TITLE, DESCRIPTION) VALUES
(TO_DATE('2024-07-30', 'YYYY-MM-DD'), '安全升级', '加强了系统安全防护，增加了多级权限管理');

INSERT INTO SYSTEM_TIMELINE (EVENT_DATE, TITLE, DESCRIPTION) VALUES
(TO_DATE('2024-11-10', 'YYYY-MM-DD'), '新功能添加', '上线了智能推荐功能，提升用户体验');

-- 提交事务
COMMIT;

-- 查询插入的数据
SELECT * FROM SYSTEM_TIMELINE ORDER BY EVENT_DATE DESC;